### ISSUE TITLE
Issues&Questions about vision observation

### ISSUE THREAD

**Issue by ziyc** [ShaneFlandermeyer/tdmpc2-jax#10]
Hi @ShaneFlandermeyer, thanks you so much for brining out this nice work! Its really fast!

I encountered an issue when I tried to use rgb for observation by
`python train.py env.backend=dmc env.env_id=dog-run env.dmc.obs_type=rgb`

got this error (note that the code works well when `env.dmc.obs_type=state` in the same command):
![image](https://github.com/user-attachments/assets/b6a348ef-9cf4-42ba-a44b-f289821cfbf4)

Does this codebase currently support vision observation? If it supports, could you please provides some insights about its convergence speed? I noticed that for the dog-run task with state as observation, the training time is about 2 hours on my 4090. If using RGB or depthmap as observation, how long might it possibly take?

Thank you for your time!

**Comment by ShaneFlandermeyer** [comment]
Hi,

While there's no built-in option for image inputs, it should be easy to change the encoder to a CNN model by replacing lines 78-85 in ```train.py``` with your vision model of choice. I have done this for graph networks in my personal research with no trouble, but let me know if you run into problems!

**Comment by ziyc** [comment]
Hi @ShaneFlandermeyer, thank you so much for the rapid reply!

Yeah, the error occurs before model creation, I've fixed this issue by modifying the arguments of the `reset()` fn in `PixelWrapper`
![image](https://github.com/user-attachments/assets/6c98e4a4-6b3f-492a-9a8b-52f96be73ca8)

But here came the next issue, 
![image](https://github.com/user-attachments/assets/75120046-3a26-42fe-86b0-93c3c7aa5b01)

Does this jax version support rgb observation? From the code is seems to get this part implemented:
https://github.com/ShaneFlandermeyer/tdmpc2-jax/blob/d9d95b51b04b39c45d6f16c0b907ace90871bcbf/tdmpc2_jax/envs/dmcontrol.py#L206-L208

but I can't successfully run any command with `env.dmc.obs_type=rgb`

I'm currently benchmarking tdmpc2 with rgb observation, I'm wondering how long it takes for a single task to converge, your insights would be very helpful to my research, thank you so much!

**Comment by ShaneFlandermeyer** [comment]
That appears to be an issue with dmc rather than this repo. Have you tried the instructions in the "Rendering" section of their readme?

https://github.com/google-deepmind/dm_control

**Comment by ziyc** [comment]
Thanks! I'll check it.

**Comment by ShaneFlandermeyer** [comment]
Closing this issue.
