### ISSUE TITLE
Environment Setup

### ISSUE THREAD

**Issue by Ozzey** [ShaneFlandermeyer/tdmpc2-jax#2]
Hello! Amazing work with the jax implementation and vectorization. I wanted to ask could you please give me some pointers on how to use this implementation for custom gym/ mujoco-gym env?  Assuming it's continuous control with a simple vector for the state.

**Comment by ShaneFlandermeyer** [comment]
Using custom gym envs is pretty straightforward with the current setup! All you need to do is register the env (see [here](https://www.gymlibrary.dev/content/environment_creation/#registering-envs)), then change the env_id field in the config file to whatever ID you use in gym.register().

**Comment by Ozzey** [comment]
> Using custom gym envs is pretty straightforward with the current setup! All you need to do is register the env (see [here](https://www.gymlibrary.dev/content/environment_creation/#registering-envs)), then change the env_id field in the config file to whatever ID you use in gym.register().

Great! Thank you for the response. Closing the issue.
