### ISSUE TITLE
Saving trained model

### ISSUE THREAD

**Issue by Ozzey** [ShaneFlandermeyer/tdmpc2-jax#3]
Is there any plans on adding support for saving single/multi-task trained models and continued training of these models?

**Comment by ShaneFlandermeyer** [comment]
I plan to add a save/load feature in the not-so-distant future. If you would like to do it right now, you should be able to add [Orbax checkpoints](https://flax.readthedocs.io/en/latest/guides/training_techniques/use_checkpointing.html) into the main training loop without much trouble. 

I only consider single-task scenarios in my research, so multi-task models are low on my list of priorities. I would gladly welcome any pull requests if that's a highly desired feature though :)

**Comment by Ozzey** [comment]
Great! I am working on making your JAX implementation of TDMPC2 more OOP based which would have a structure similar to SB3 algorithms. I'll try to add multitasking and Checkpoints and then maybe you can test it if possible?

**Comment by ShaneFlandermeyer** [comment]
Thanks to some recent contributions in #4, we now have checkpointing and tensorboard logging in the develop branch! Closing this issue now.
